### ISSUE TITLE
jse 崩溃

### ISSUE THREAD

**Issue by forcux** [ikkz/bext#127]
新建空对象，试图添加子节点时页面崩了

错误
react-dom.production.min.js:216

TypeError: Invalid attempt to spread non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
    at Fi (nonIterableSpread.js:2:9)
    at Si (toConsumableArray.js:6:95)
    at PathContext.js:13:47
    at Object.useMemo (react-dom.production.min.js:172:115)
    at Object.k (react.production.min.js:23:113)
    at Tw (PathContext.js:12:10)
    at Iw (MenuItem.js:204:26)
    at ga (react-dom.production.min.js:157:137)
    at rl (react-dom.production.min.js:267:460)
    at jl (react-dom.production.min.js:250:347)

奇怪的是，本地 start ， ?jse-dev 通通没有问题，
jse 这边重新部署，升级依赖，都没有解决
尝试了重新部署，升级 jsev 依赖，没有用

**Comment by forcux** [comment]
已解决，更换 minifier 为 swc
